### ISSUE TITLE
Overlays not being drawn

### ISSUE THREAD

**Issue by drsmall** [coldiary/react-image-mapper#1]
Uncaught TypeError: this.context.beginPath is not a function
Uncaught TypeError: this.context.clearRect is not a function

Steps to reproduce:
1. npm install react-image-mapper --save
2. Imported using import ImageMapper from 'react-image-mapper';
3. Pasted example code from demo website into project

**Comment by coldiary** [comment]
Could you provide info about the browser, the complete code example, and build-system you are using ?

**Comment by drsmall** [comment]
Yeah I'm using Chrome Version 58.0.3029.96 (64-bit)
Webpack for builds
`generateImageMap(){
    var URL = "./media/room/room_0.png";
    var MAP = {
      name: "my-map",
      areas: [
        { shape: "poly", coords: [25,33, 27,300 ,128,240 ,128,94] },
        { shape: "poly", coords: [219,118,220,210,283,210,284,119] },
        { shape: "poly", coords: [381,241,383,94,462,53,457,282] },
        { shape: "poly", coords: [245,285,290,285,274,239,249,238] }
      ]
    };

    return (
      <div>
        {/*<ImageMapper src={URL} map={MAP} width={750}/>*/}
      </div>
    );
  }`

**Comment by coldiary** [comment]
Well, I had to spam refresh to see the error somehow. Turns out it was a really poor choice to name the property `context` since it's commonly used by react itself.

I just pushed some changes Could you tell me if the problem is still occuring ?

**Comment by drsmall** [comment]
Working just fine now.
