### ISSUE TITLE
Feature Request: Colored Areas

### ISSUE THREAD

**Issue by janhartmann** [coldiary/react-image-mapper#15]
Thanks for this great library, exactly what I was looking for. 

I do, however, have a feature request when you feel you have the time for it. :-)

I have an image map where I would like to highlight some areas, even when they are not hovered. For example I have a few places I would like to have a yellow polygon and somewhere some reds. 

If it was possible to specify a `className', color etc. from the map options object and wether or not the area should be always be shown - that would be cool!

All the best!

**Comment by filiperodrigues1992** [comment]
I like that idea, I wanted something similar. When you click in an area, that area stays "hovered". I tried adding a div on top of the image, and it works fine for the top image elements. But the image is inside another div and is scrollable, so just adding another div on top of it wont follow the scroll. @janhartmann if your image isn't scrollable, you could add divs based on coordinates on the "onLoad" function. 

![screen shot 2018-12-18 at 12 33 33 pm](https://user-images.githubusercontent.com/45214703/50171741-44ef7c00-02c1-11e9-8370-f6df76d5691c.png)
![screen shot 2018-12-18 at 12 33 43 pm](https://user-images.githubusercontent.com/45214703/50171742-44ef7c00-02c1-11e9-9f70-1cfbd89d4d43.png)

**Comment by janhartmann** [comment]
Hi again

I was in a bit of a hurry of this feature, that I actually forked your repository and make the changes my self. I am a TypeScript user, so I also converted the code base to TypeScript and make some minor modifications to the original source of yours.

I have added a playground here with my changes - if you need some inspiration! :)

https://codesandbox.io/s/zzxm6mzkzx

**Comment by filiperodrigues1992** [comment]
I was also able to do what I needed, but since I haven't the knowledge to change the actual code base, I feel like mine is more like a hack.
Here's what I did:
1) To the ImageMapper component I am also sending the index of the area like:
`onClick={(area, index) => this.clicked(area, index)}`

2) At the onClick function I added:

```//calculate style attributes
    width = area.coords[2] - area.coords[0] + "px"
    height = area.coords[3] - area.coords[1] + "px"
    marginTop = area.coords[1] + "px"
    marginLeft = area.coords[0] + "px"    

    // remove class from previous clicked and add to current clicked 
    $('[name="my-map"]').find("area").removeClass( "elementClicked" );
    $('[name="my-map"]').find("area").removeAttr( "style" );
    $('[name="my-map"]').find("area").eq(index).addClass( "elementClicked" );

   // Change the class to be where the area is
    $(".elementClicked").css('width', width)
    $(".elementClicked").css('height', height)
    $(".elementClicked").css('margin-top', marginTop)
    $(".elementClicked").css('margin-left', marginLeft)```

I know is definitely the best way, but is working for now.

**Comment by mrtrebor** [comment]
[Please take a look at pull, im curious about your opinions](https://github.com/coldiary/react-image-mapper/pull/16)

**Comment by coldiary** [comment]
I'll take a look at the pull request soon, in the following days.
I apologize for having no time to keep this package up to date lately.

**Comment by coldiary** [comment]
#20 merged
