### ISSUE TITLE
getTipPosition code for circles...

### ISSUE THREAD

**Issue by MichaelLiss** [coldiary/react-image-mapper#17]
I think the sample code should be updated to put the label in the center of the circle as follows:

    getTipPosition(area) {
    
    let a = { y:0, x:0 };

    if (area){

        //console.log("in area " + area.name + " getting position from " + area.coords);

        if(area.shape === 'poly' || area.shape === 'rect'){
            // Calculate centroid
            const n = area.coords.length / 2;
            a = area.coords.reduce(({ y, x }, val, idx) => 
                { return !(idx % 2) ? { y, x: x + (val / n) } : { y: y + (val / n), x }; }, { y: 0, x: 0 }
            );

        } else if(area.shape === 'circle'){
            //console.log(area.coords[0]); // x 
            //console.log(area.coords[1]); // y
            //console.log(area.coords[2]); // radius
            a = {y: area.coords[1], x: area.coords[0]};
        }
    }

    //console.log("result x:" + a.x + " y:" + a.y);

    return { top: `${a.y}px`, left: `${a.x}px` };
}

**Comment by coldiary** [comment]
Thanks for the suggestion, I'll update the sample code soon, when I'll get some time to do it.
Keeping this issue open until then.

**Comment by MichaelLiss** [comment]
super cool  !!... 
hey.. as an aside... do you have any code that will display an image with the correct aspect ratio ?

**Comment by coldiary** [comment]
What do you mean by that ? Do you have an example that shows the issue ?
If only one dimension is specified, aspect ratio should be respected.

**Comment by MichaelLiss** [comment]
yes: 
https://codesandbox.io/s/5k17okkqrp

**Comment by coldiary** [comment]
Relates to #18 I think, so close it now it's resolved.
