### ISSUE TITLE
Show all areas by default

### ISSUE THREAD

**Issue by kerron** [coldiary/react-image-mapper#20]
As a user I would like to see all areas that are interactive (have mouse events) without first having to hover over the image or an area.

**Comment by coldiary** [comment]
What about an option that add a zone in the corner which, when hovered, highlight every interactive area on the image. Would that be beneficial ?
We can also add a an animation before first interaction, which cyclicly highlight areas to show where they are, if that answer the request.

**Comment by mrtrebor** [comment]
According to [my answer](https://github.com/coldiary/react-image-mapper/issues/19) you could use preFillColor attribute to specify background for given areas (maybe with some transparency) and if needed change that during user actions.

Idea about animation is also cool.

**Comment by coldiary** [comment]
In the first time, I'll close this issue after merging your PR @mrtrebor, if it's ok with @kerron to use your feature for his goal.
I'll add some enhancement on that on a ROADMAP file

**Comment by kerron** [comment]
@coldiary, The project I am using this in is primarily used on mobile devices so the hover effect won't be super useful for me. I am primarily using the `onClick` event. Hence why my initial request was to have the areas visible on load (circumventing the need to hover). 

That said,  "add a an animation before first interaction" sound like a super cool feature, and would defo request this! As long as it doesn't require hover events :)

@mrtrebor, your [PR](https://github.com/coldiary/react-image-mapper/pull/16) seems to meet my initial request. Is this the use case:
```
<ImageMapper src={SRC} map={MAP} preFillColor={`rgba(255, 255, 255, 0)`}/>
```

Thanks both!
