### ISSUE TITLE
z Index in example could be wrong... ?

### ISSUE THREAD

**Issue by MichaelLiss** [coldiary/react-image-mapper#21]
Hi,

I setup and started working with the example and the little black boxes with numbers (when you mouse over the shape) would not appear.  It took me hours to figure out why.  (I am using the latest version of chrome).

In the example the z index is specified as :

    zindex: 1000;

It started working when I read another article that also had a Z index, and changed the css for the ImageMapper to: 

    z-index: 1000;

**Comment by mrtrebor** [comment]
[In example's .less file it's "z-index"](https://github.com/coldiary/react-image-mapper/blob/master/example/src/example.less)

[But in example.js it figures as "zIndex"](https://github.com/coldiary/react-image-mapper/blob/master/example/src/example.js) it's just like little typo.

**Comment by MichaelLiss** [comment]
I hear you... but that little "typo" if not corrected, will not show the tool tip boxes!  which is one of the better features of this component, IMHO.  :-)

**Comment by coldiary** [comment]
I've corrected the example, thanks for pointing out the typo.
