### ISSUE TITLE
Mouse X,Y position while moving the mouse in the image

### ISSUE THREAD

**Issue by MichaelLiss** [coldiary/react-image-mapper#23]
I would like to receive mouse X,Y locations when moving across the image.

**Comment by mrtrebor** [comment]
[Just use approach given in this SO answer.](https://stackoverflow.com/a/42183459)

**Comment by MichaelLiss** [comment]
mrtrebor... when I put that code into the ImageMapper, I never receive the mouse X,Y position:

                <ImageMapper 
                    src={this.state.mappedImage.imageUrl} 
                    map={this.state.mappedImage.MAP} 
                    width={1000}
                    imgWidth={500}

                    onLoad={() => this.load()}
                    onClick={(area, index) => this.onClickedInsideImage(area, index)}
                    onMouseEnter={(area, index) => this.enterArea(area, index)}
                    onMouseLeave={(area, index) => this.leaveArea(area, index)}
                    onImageClick={evt => this.onClickedOutsideImage(evt)}
                    **onMouseMove={this._onMouseMove.bind(this)}**
                />

**Comment by coldiary** [comment]
He propose to bind on the mouse mouvement of a container parent of the mapper having the same size.

 But it can be added to the mapper itself, if i have time to add it, or anyone can propose a PR and I'd give a look.

**Comment by MichaelLiss** [comment]
If the onMouseMove is bound to the parent, it gives parent X,Y coordinates and the parent may or may not always have the same size as the imageMapper, thereby creating a scaling issue. 
-
I know, I tried binding it to the parent and my parent is a different size.

**Comment by coldiary** [comment]
Just release v0.0.11 that add `onMouseMove` and `onImageMouseMove` event handler.
Let me know if that answers your needs.

**Comment by MichaelLiss** [comment]
Thank you very much...  nice job !  IMO, just what it needed !
