### ISSUE TITLE
return center point of area

### ISSUE THREAD

**Issue by MichaelLiss** [coldiary/react-image-mapper#24]
It would be nice if the area returned had the center point (x,y).

This solves two problems:

1. Calculating the center point in a function 
2. Scaling the center point independently from the image

**Comment by MichaelLiss** [comment]
:-) 
any luck with this one?

**Comment by coldiary** [comment]
Just released a v0.0.10 and updated example. Thanks for the suggestion :)

**Comment by MichaelLiss** [comment]
Works like a charm... thank you so much !
