### ISSUE TITLE
Mandatory onMouseMove function?

### ISSUE THREAD

**Issue by bmakan** [coldiary/react-image-mapper#26]
Seems like the function `onMouseMove` is mandatory because when I don't supply it I get the following error: `TypeError: _this4.props.onMouseMove is undefined`.

Could be a bug in the implementation or an intended thing. If it is intended, please add this information to the documentation. Also, in this case, I don't think it should be mandatory. I ended up putting `() -> undefined` at its place.

Version: 0.0.11

**Comment by coldiary** [comment]
This should not be mandatory. I'll have to patch it, but have no time currently. Any PR would be welcome for that.

**Comment by coldiary** [comment]
I've published a new version (v0.0.14) where they should not be mandatory anymore.
