### ISSUE TITLE
TypeError: Cannot read property 'bool' of undefined

### ISSUE THREAD

**Issue by MikeyFriedChicken** [coldiary/react-image-mapper#3]
If you check the example at:
https://npm.runkit.com/react-image-mapper 

You get this error:
**TypeError: Cannot read property 'bool' of undefined**

I also get this when I try and use it in my react project.

**Comment by coldiary** [comment]
Made a release with the change suggested.
Should you confirm that the issue is fixed for you, and I'll close this issue.
Thanks again for reminding me about the deprecated package, I forgot to update that one !

**Comment by MikeyFriedChicken** [comment]
Thank you very much.  I will test this and confirm

**Comment by coldiary** [comment]
Closing as no confirmation (but can be reopened if problems occurs again).
