### ISSUE TITLE
Component installation in reactjs but not updated version

### ISSUE THREAD

**Issue by Bombe93** [coldiary/react-image-mapper#7]
You have not updated the file inside the 'lib' folder, maybe it's better to update it when you release an update on npm.
I had to download the repo separately and get the build.

Thanks

**Comment by coldiary** [comment]
Oops, you're entirely right.
Should be fixed by now, could you confirm ?
Thanks for pointing that out

**Comment by Bombe93** [comment]
ok now it seems okay, thanks
