### ISSUE TITLE
live demo with onClick & other callbacks?

### ISSUE THREAD

**Issue by WandHerring** [coldiary/react-image-mapper#8]
Hello,

First of all, I want to say thank you for your component, it really plugs a hole in the html 5 functionalities. 

Now, as I'm trying to figure things out I have to say the example is a bit bare-bone. Being mostly self-thought in React & Javascript in general, I'm struggling a bit to adapt the OnClick instructions to actually make it works. Would it be possible to update the live demo to showcase more functionalities?

Thank you in advance!
Greg

**Comment by coldiary** [comment]
Hi ! Thank you for your interest.

I've just updated the demo page with callbacks on the example image.
I did not include the code of the function though, it simply take the argument to output a formatted string under the image.
Let me know if it helps, I can add the full details if needed !
